version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/aws"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/terraform/cloudflare"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/terraform/github"
    schedule:
      interval: "monthly"
